# Introduction to PyTorch

In [0]:
import torch

### torch.empty()

In [2]:
# Returns a tensor filled with uninitialized data. The shape of the tensor is defined by the variable argument size
x = torch.empty(5, 3)
print(x)
print(x.size())
print(type(x))
print(x[0][0])

tensor([[2.8189e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])
torch.Size([5, 3])
<class 'torch.Tensor'>
tensor(2.8189e-36)


In [3]:
print(x + 1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### torch.rand()

In [4]:
# Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
x = torch.rand(5, 3)
print(x)
print(x.size())
print(type(x))
print(x[0][0])

tensor([[0.0888, 0.5874, 0.5945],
        [0.0856, 0.3307, 0.6614],
        [0.6487, 0.5533, 0.9025],
        [0.0705, 0.1185, 0.0775],
        [0.3821, 0.6653, 0.5956]])
torch.Size([5, 3])
<class 'torch.Tensor'>
tensor(0.0888)


In [5]:
print(x + 1)
print(x - 1)

tensor([[1.0888, 1.5874, 1.5945],
        [1.0856, 1.3307, 1.6614],
        [1.6487, 1.5533, 1.9025],
        [1.0705, 1.1185, 1.0775],
        [1.3821, 1.6653, 1.5956]])
tensor([[-0.9112, -0.4126, -0.4055],
        [-0.9144, -0.6693, -0.3386],
        [-0.3513, -0.4467, -0.0975],
        [-0.9295, -0.8815, -0.9225],
        [-0.6179, -0.3347, -0.4044]])


In [6]:
print(torch.add(x,1))
print(torch.sub(x,1))

tensor([[1.0888, 1.5874, 1.5945],
        [1.0856, 1.3307, 1.6614],
        [1.6487, 1.5533, 1.9025],
        [1.0705, 1.1185, 1.0775],
        [1.3821, 1.6653, 1.5956]])
tensor([[-0.9112, -0.4126, -0.4055],
        [-0.9144, -0.6693, -0.3386],
        [-0.3513, -0.4467, -0.0975],
        [-0.9295, -0.8815, -0.9225],
        [-0.6179, -0.3347, -0.4044]])


### torch.Tensor()

In [7]:
x = torch.rand(5, 3)
result = torch.Tensor(5, 3)
print(x)
print(result)

tensor([[0.9524, 0.4399, 0.6278],
        [0.7049, 0.3303, 0.7383],
        [0.6939, 0.1188, 0.4304],
        [0.6852, 0.8645, 0.6403],
        [0.3059, 0.2345, 0.4043]])
tensor([[2.8190e-36, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 6.6140e-01],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 6.6532e-01, 5.9564e-01]])


In [8]:
torch.add(x, 1, out=result)
print(result)
torch.sub(x, 1, out=result)
print(result)
torch.mul(x, 2, out=result)
print(result)
torch.div(x, 2, out=result)
print(result)

tensor([[1.9524, 1.4399, 1.6278],
        [1.7049, 1.3303, 1.7383],
        [1.6939, 1.1188, 1.4304],
        [1.6852, 1.8645, 1.6403],
        [1.3059, 1.2345, 1.4043]])
tensor([[-0.0476, -0.5601, -0.3722],
        [-0.2951, -0.6697, -0.2617],
        [-0.3061, -0.8812, -0.5696],
        [-0.3148, -0.1355, -0.3597],
        [-0.6941, -0.7655, -0.5957]])
tensor([[1.9048, 0.8797, 1.2557],
        [1.4099, 0.6607, 1.4766],
        [1.3879, 0.2376, 0.8609],
        [1.3703, 1.7289, 1.2805],
        [0.6117, 0.4689, 0.8087]])
tensor([[0.4762, 0.2199, 0.3139],
        [0.3525, 0.1652, 0.3691],
        [0.3470, 0.0594, 0.2152],
        [0.3426, 0.4322, 0.3201],
        [0.1529, 0.1172, 0.2022]])


In [9]:
x = torch.rand(5, 3)
print(x.add(1))
print(x)

tensor([[1.5064, 1.0514, 1.9270],
        [1.3803, 1.3476, 1.3257],
        [1.3508, 1.3707, 1.7989],
        [1.5159, 1.3958, 1.9565],
        [1.3406, 1.4215, 1.9649]])
tensor([[0.5064, 0.0514, 0.9270],
        [0.3803, 0.3476, 0.3257],
        [0.3508, 0.3707, 0.7989],
        [0.5159, 0.3958, 0.9565],
        [0.3406, 0.4215, 0.9649]])


In [10]:
print(x.add_(1)) # mutates the tensor in place
print(x)

tensor([[1.5064, 1.0514, 1.9270],
        [1.3803, 1.3476, 1.3257],
        [1.3508, 1.3707, 1.7989],
        [1.5159, 1.3958, 1.9565],
        [1.3406, 1.4215, 1.9649]])
tensor([[1.5064, 1.0514, 1.9270],
        [1.3803, 1.3476, 1.3257],
        [1.3508, 1.3707, 1.7989],
        [1.5159, 1.3958, 1.9565],
        [1.3406, 1.4215, 1.9649]])


In [11]:
print(x.add_(1)) # mutates the tensor in place
print(x.sub_(1))
print(x.mul_(1))
print(x.div_(1))

tensor([[2.5064, 2.0514, 2.9270],
        [2.3803, 2.3476, 2.3257],
        [2.3508, 2.3707, 2.7989],
        [2.5159, 2.3958, 2.9565],
        [2.3406, 2.4215, 2.9649]])
tensor([[1.5064, 1.0514, 1.9270],
        [1.3803, 1.3476, 1.3257],
        [1.3508, 1.3707, 1.7989],
        [1.5159, 1.3958, 1.9565],
        [1.3406, 1.4215, 1.9649]])
tensor([[1.5064, 1.0514, 1.9270],
        [1.3803, 1.3476, 1.3257],
        [1.3508, 1.3707, 1.7989],
        [1.5159, 1.3958, 1.9565],
        [1.3406, 1.4215, 1.9649]])
tensor([[1.5064, 1.0514, 1.9270],
        [1.3803, 1.3476, 1.3257],
        [1.3508, 1.3707, 1.7989],
        [1.5159, 1.3958, 1.9565],
        [1.3406, 1.4215, 1.9649]])


In [15]:
print(x[1,:])

tensor([1.3803, 1.3476, 1.3257])


### torch.ones() & torch.zeros()

In [13]:
ones = torch.ones(5, 3)
zeros = torch.zeros(5, 3)
print(ones)
print(zeros)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
